In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pycrystem as pc
import hyperspy.api as hs
%matplotlib tk

In [2]:
N = 10
grid_size = int(2**N)

Choosing N != integer 

In [3]:
image = np.zeros([grid_size,grid_size])

This is our blank slate

In [4]:
number_of_peaks = 3 
peak_locations = np.random.random(size=[number_of_peaks,2])*grid_size
peak_locations

array([[ 744.21366711,  216.44168605],
       [ 347.71945611,  140.09115914],
       [ 700.10715619,  632.39290071]])

We now have peaks, they have float locations

In [21]:
sample_size = 50000 #physically what is this?
peak_data = np.full([sample_size*number_of_peaks,2],fill_value=np.nan) #this is for error detection

In [22]:
for i in np.arange(0,number_of_peaks,1):
    peak_data[i*sample_size :(i+1)*sample_size] = \
    np.random.multivariate_normal(peak_locations[i],10*np.eye(2,2),size=sample_size)

In [23]:
# check no nan values are left.

In [24]:
discrete_data = np.rint(peak_data).astype(int)

In [25]:
for signal_location in discrete_data:
    image[signal_location[0],signal_location[1]] =+ 1

In [26]:
discrete_data

array([[744, 222],
       [748, 218],
       [736, 213],
       ..., 
       [700, 632],
       [697, 631],
       [699, 636]])

In [27]:
plt.imshow(image)

This marks the end of image preperation (noise and rebinning come later)

In [28]:
dp = pc.ElectronDiffraction(image)

In [29]:
peaks_recovered = dp.find_peaks('laplacian_of_gaussians')
peaks_recovered.data += grid_size/2

A Jupyter Widget

A Jupyter Widget

In [30]:
peaks_recovered.data[:,0]

array([ 744.,  700.,  348.])

In [31]:
mmx,mmy = peaks_recovered.data[:,1],peaks_recovered.data[:,0]

dp.plot(cmap='viridis') 
for mx,my in zip(mmx,mmy):
    m = hs.markers.point(x=mx,y=my,color='red',marker='x')
    dp.add_marker(m,plot_marker=True,permanent=False)

In [83]:
import skimage as ski

In [90]:
ski.feature.blob_log(image,min_sigma=0.2,max_sigma=10,overlap=0.2)

array([[  2.57000000e+02,   1.98000000e+02,   2.00000000e-01],
       [  2.56000000e+02,   2.04000000e+02,   2.00000000e-01],
       [  2.54000000e+02,   2.01000000e+02,   2.37777778e+00],
       [  2.50000000e+02,   2.01000000e+02,   2.00000000e-01],
       [  1.53000000e+02,   4.90000000e+01,   2.00000000e-01],
       [  1.52000000e+02,   5.30000000e+01,   2.37777778e+00],
       [  1.50000000e+02,   4.90000000e+01,   2.00000000e-01],
       [  1.49000000e+02,   5.50000000e+01,   2.00000000e-01],
       [  1.48000000e+02,   5.20000000e+01,   2.00000000e-01],
       [  1.16000000e+02,   2.17000000e+02,   2.37777778e+00]])

In [93]:
dp.isig[216].plot()